[build]
  publish = "."
  
[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Hidden test routes for logo carousel development
[[redirects]]
  from = "/logo-test"
  to = "/logo-carousel-clean.html"
  status = 200
  force = true

[[redirects]]
  from = "/logo-variations-test"
  to = "/logo-variations.html"
  status = 200
  force = true

[[redirects]]
  from = "/test-logos-v2"
  to = "/logo-variations-v2.html"
  status = 200
  force = true


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"